/*
Bare Metal Cloud API

Create, power off, power on, reset, reboot, or shut down your server with the Bare Metal Cloud API. Deprovision servers, get or edit SSH key details, and a lot more. Manage your infrastructure more efficiently using just a few simple api calls.<br> <br> <span class=\"pnap-api-knowledge-base-link\"> Knowledge base articles to help you can be found <a href='https://phoenixnap.com/kb/how-to-deploy-bare-metal-cloud-server' target='_blank'>here</a> </span><br> <br> <b>All URLs are relative to (https://api.phoenixnap.com/bmc/v1/)</b>

API version: 0.1
Contact: support@phoenixnap.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bmcapi

import (
	"encoding/json"
)

// QuotaEditLimitRequest A request to change the limit on a quota.
type QuotaEditLimitRequest struct {
	// The new limit that is requested.
	Limit int32 `json:"limit"`
	// The reason for changing the limit.
	Reason string `json:"reason"`
}

// NewQuotaEditLimitRequest instantiates a new QuotaEditLimitRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuotaEditLimitRequest(limit int32, reason string) *QuotaEditLimitRequest {
	this := QuotaEditLimitRequest{}
	this.Limit = limit
	this.Reason = reason
	return &this
}

// NewQuotaEditLimitRequestWithDefaults instantiates a new QuotaEditLimitRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuotaEditLimitRequestWithDefaults() *QuotaEditLimitRequest {
	this := QuotaEditLimitRequest{}
	return &this
}

// GetLimit returns the Limit field value
func (o *QuotaEditLimitRequest) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *QuotaEditLimitRequest) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *QuotaEditLimitRequest) SetLimit(v int32) {
	o.Limit = v
}

// GetReason returns the Reason field value
func (o *QuotaEditLimitRequest) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *QuotaEditLimitRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *QuotaEditLimitRequest) SetReason(v string) {
	o.Reason = v
}

func (o QuotaEditLimitRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["limit"] = o.Limit
	}
	if true {
		toSerialize["reason"] = o.Reason
	}
	return json.Marshal(toSerialize)
}

type NullableQuotaEditLimitRequest struct {
	value *QuotaEditLimitRequest
	isSet bool
}

func (v NullableQuotaEditLimitRequest) Get() *QuotaEditLimitRequest {
	return v.value
}

func (v *NullableQuotaEditLimitRequest) Set(val *QuotaEditLimitRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQuotaEditLimitRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQuotaEditLimitRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuotaEditLimitRequest(val *QuotaEditLimitRequest) *NullableQuotaEditLimitRequest {
	return &NullableQuotaEditLimitRequest{value: val, isSet: true}
}

func (v NullableQuotaEditLimitRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuotaEditLimitRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
