/*
Bare Metal Cloud API

Create, power off, power on, reset, reboot, or shut down your server with the Bare Metal Cloud API.  Deprovision servers, get or edit SSH key details, assign public IPs, assign servers to networks and a lot more.  Manage your infrastructure more efficiently using just a few simple API calls.<br> <br> <span class='pnap-api-knowledge-base-link'> Knowledge base articles to help you can be found <a href='https://phoenixnap.com/kb/how-to-deploy-bare-metal-cloud-server' target='_blank'>here</a> </span><br> <br> <b>All URLs are relative to (https://api.phoenixnap.com/bmc/v1/)</b> 

API version: 0.1
Contact: support@phoenixnap.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bmcapi

import (
	"encoding/json"
)

// OsConfigurationMapProxmox Proxmox VE configuration properties.
type OsConfigurationMapProxmox struct {
	// Password set for user root on a Proxmox server which will only be returned in response to provisioning a server.
	RootPassword *string `json:"rootPassword,omitempty"`
	// The URL of the management UI which will only be returned in response to provisioning a server.
	ManagementUiUrl *string `json:"managementUiUrl,omitempty"`
	// List of IPs allowed to access the Management UI. Supported in single IP, CIDR and range format. When undefined, Management UI is disabled. This will only be returned in response to provisioning a server.
	ManagementAccessAllowedIps *[]string `json:"managementAccessAllowedIps,omitempty"`
}

// NewOsConfigurationMapProxmox instantiates a new OsConfigurationMapProxmox object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOsConfigurationMapProxmox() *OsConfigurationMapProxmox {
	this := OsConfigurationMapProxmox{}
	return &this
}

// NewOsConfigurationMapProxmoxWithDefaults instantiates a new OsConfigurationMapProxmox object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOsConfigurationMapProxmoxWithDefaults() *OsConfigurationMapProxmox {
	this := OsConfigurationMapProxmox{}
	return &this
}

// GetRootPassword returns the RootPassword field value if set, zero value otherwise.
func (o *OsConfigurationMapProxmox) GetRootPassword() string {
	if o == nil || o.RootPassword == nil {
		var ret string
		return ret
	}
	return *o.RootPassword
}

// GetRootPasswordOk returns a tuple with the RootPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OsConfigurationMapProxmox) GetRootPasswordOk() (*string, bool) {
	if o == nil || o.RootPassword == nil {
		return nil, false
	}
	return o.RootPassword, true
}

// HasRootPassword returns a boolean if a field has been set.
func (o *OsConfigurationMapProxmox) HasRootPassword() bool {
	if o != nil && o.RootPassword != nil {
		return true
	}

	return false
}

// SetRootPassword gets a reference to the given string and assigns it to the RootPassword field.
func (o *OsConfigurationMapProxmox) SetRootPassword(v string) {
	o.RootPassword = &v
}

// GetManagementUiUrl returns the ManagementUiUrl field value if set, zero value otherwise.
func (o *OsConfigurationMapProxmox) GetManagementUiUrl() string {
	if o == nil || o.ManagementUiUrl == nil {
		var ret string
		return ret
	}
	return *o.ManagementUiUrl
}

// GetManagementUiUrlOk returns a tuple with the ManagementUiUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OsConfigurationMapProxmox) GetManagementUiUrlOk() (*string, bool) {
	if o == nil || o.ManagementUiUrl == nil {
		return nil, false
	}
	return o.ManagementUiUrl, true
}

// HasManagementUiUrl returns a boolean if a field has been set.
func (o *OsConfigurationMapProxmox) HasManagementUiUrl() bool {
	if o != nil && o.ManagementUiUrl != nil {
		return true
	}

	return false
}

// SetManagementUiUrl gets a reference to the given string and assigns it to the ManagementUiUrl field.
func (o *OsConfigurationMapProxmox) SetManagementUiUrl(v string) {
	o.ManagementUiUrl = &v
}

// GetManagementAccessAllowedIps returns the ManagementAccessAllowedIps field value if set, zero value otherwise.
func (o *OsConfigurationMapProxmox) GetManagementAccessAllowedIps() []string {
	if o == nil || o.ManagementAccessAllowedIps == nil {
		var ret []string
		return ret
	}
	return *o.ManagementAccessAllowedIps
}

// GetManagementAccessAllowedIpsOk returns a tuple with the ManagementAccessAllowedIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OsConfigurationMapProxmox) GetManagementAccessAllowedIpsOk() (*[]string, bool) {
	if o == nil || o.ManagementAccessAllowedIps == nil {
		return nil, false
	}
	return o.ManagementAccessAllowedIps, true
}

// HasManagementAccessAllowedIps returns a boolean if a field has been set.
func (o *OsConfigurationMapProxmox) HasManagementAccessAllowedIps() bool {
	if o != nil && o.ManagementAccessAllowedIps != nil {
		return true
	}

	return false
}

// SetManagementAccessAllowedIps gets a reference to the given []string and assigns it to the ManagementAccessAllowedIps field.
func (o *OsConfigurationMapProxmox) SetManagementAccessAllowedIps(v []string) {
	o.ManagementAccessAllowedIps = &v
}

func (o OsConfigurationMapProxmox) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RootPassword != nil {
		toSerialize["rootPassword"] = o.RootPassword
	}
	if o.ManagementUiUrl != nil {
		toSerialize["managementUiUrl"] = o.ManagementUiUrl
	}
	if o.ManagementAccessAllowedIps != nil {
		toSerialize["managementAccessAllowedIps"] = o.ManagementAccessAllowedIps
	}
	return json.Marshal(toSerialize)
}

type NullableOsConfigurationMapProxmox struct {
	value *OsConfigurationMapProxmox
	isSet bool
}

func (v NullableOsConfigurationMapProxmox) Get() *OsConfigurationMapProxmox {
	return v.value
}

func (v *NullableOsConfigurationMapProxmox) Set(val *OsConfigurationMapProxmox) {
	v.value = val
	v.isSet = true
}

func (v NullableOsConfigurationMapProxmox) IsSet() bool {
	return v.isSet
}

func (v *NullableOsConfigurationMapProxmox) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOsConfigurationMapProxmox(val *OsConfigurationMapProxmox) *NullableOsConfigurationMapProxmox {
	return &NullableOsConfigurationMapProxmox{value: val, isSet: true}
}

func (v NullableOsConfigurationMapProxmox) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOsConfigurationMapProxmox) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


