/*
Bare Metal Cloud API

Create, power off, power on, reset, reboot, or shut down your server with the Bare Metal Cloud API.  Deprovision servers, get or edit SSH key details, assign public IPs, assign servers to networks and a lot more.  Manage your infrastructure more efficiently using just a few simple API calls.<br> <br> <span class='pnap-api-knowledge-base-link'> Knowledge base articles to help you can be found <a href='https://phoenixnap.com/kb/how-to-deploy-bare-metal-cloud-server' target='_blank'>here</a> </span><br> <br> <b>All URLs are relative to (https://api.phoenixnap.com/bmc/v1/)</b>

API version: 0.1
Contact: support@phoenixnap.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bmcapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ReservationTransferDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReservationTransferDetails{}

// ReservationTransferDetails Reservation transfer details.
type ReservationTransferDetails struct {
	// ID of target server to transfer reservation to.
	TargetServerId       string `json:"targetServerId"`
	AdditionalProperties map[string]interface{}
}

type _ReservationTransferDetails ReservationTransferDetails

// NewReservationTransferDetails instantiates a new ReservationTransferDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReservationTransferDetails(targetServerId string) *ReservationTransferDetails {
	this := ReservationTransferDetails{}
	this.TargetServerId = targetServerId
	return &this
}

// NewReservationTransferDetailsWithDefaults instantiates a new ReservationTransferDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReservationTransferDetailsWithDefaults() *ReservationTransferDetails {
	this := ReservationTransferDetails{}
	return &this
}

// GetTargetServerId returns the TargetServerId field value
func (o *ReservationTransferDetails) GetTargetServerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetServerId
}

// GetTargetServerIdOk returns a tuple with the TargetServerId field value
// and a boolean to check if the value has been set.
func (o *ReservationTransferDetails) GetTargetServerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetServerId, true
}

// SetTargetServerId sets field value
func (o *ReservationTransferDetails) SetTargetServerId(v string) {
	o.TargetServerId = v
}

func (o ReservationTransferDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReservationTransferDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["targetServerId"] = o.TargetServerId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReservationTransferDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"targetServerId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReservationTransferDetails := _ReservationTransferDetails{}

	err = json.Unmarshal(data, &varReservationTransferDetails)

	if err != nil {
		return err
	}

	*o = ReservationTransferDetails(varReservationTransferDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "targetServerId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReservationTransferDetails struct {
	value *ReservationTransferDetails
	isSet bool
}

func (v NullableReservationTransferDetails) Get() *ReservationTransferDetails {
	return v.value
}

func (v *NullableReservationTransferDetails) Set(val *ReservationTransferDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableReservationTransferDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableReservationTransferDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReservationTransferDetails(val *ReservationTransferDetails) *NullableReservationTransferDetails {
	return &NullableReservationTransferDetails{value: val, isSet: true}
}

func (v NullableReservationTransferDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReservationTransferDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
