/*
Billing API

Automate your infrastructure billing with the Bare Metal Cloud Billing API. Reserve your server instances to ensure guaranteed resource availability for 12, 24, and 36 months. Retrieve your server’s rated usage for a given period and enable or disable auto-renewals.<br> <br> <span class='pnap-api-knowledge-base-link'> Knowledge base articles to help you can be found <a href='https://phoenixnap.com/kb/phoenixnap-bare-metal-cloud-billing-models' target='_blank'>here</a> </span><br> <br> <b>All URLs are relative to (https://api.phoenixnap.com/billing/v1/)</b>

API version: 0.1
Contact: support@phoenixnap.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billingapi

import (
	"encoding/json"
	"fmt"
)

// checks if the Utilization type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Utilization{}

// Utilization struct for Utilization
type Utilization struct {
	Quantity             Quantity `json:"quantity"`
	Percentage           float32  `json:"percentage"`
	AdditionalProperties map[string]interface{}
}

type _Utilization Utilization

// NewUtilization instantiates a new Utilization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUtilization(quantity Quantity, percentage float32) *Utilization {
	this := Utilization{}
	this.Quantity = quantity
	this.Percentage = percentage
	return &this
}

// NewUtilizationWithDefaults instantiates a new Utilization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUtilizationWithDefaults() *Utilization {
	this := Utilization{}
	return &this
}

// GetQuantity returns the Quantity field value
func (o *Utilization) GetQuantity() Quantity {
	if o == nil {
		var ret Quantity
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *Utilization) GetQuantityOk() (*Quantity, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *Utilization) SetQuantity(v Quantity) {
	o.Quantity = v
}

// GetPercentage returns the Percentage field value
func (o *Utilization) GetPercentage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Percentage
}

// GetPercentageOk returns a tuple with the Percentage field value
// and a boolean to check if the value has been set.
func (o *Utilization) GetPercentageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Percentage, true
}

// SetPercentage sets field value
func (o *Utilization) SetPercentage(v float32) {
	o.Percentage = v
}

func (o Utilization) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Utilization) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["quantity"] = o.Quantity
	toSerialize["percentage"] = o.Percentage

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Utilization) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"quantity",
		"percentage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUtilization := _Utilization{}

	err = json.Unmarshal(data, &varUtilization)

	if err != nil {
		return err
	}

	*o = Utilization(varUtilization)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "quantity")
		delete(additionalProperties, "percentage")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUtilization struct {
	value *Utilization
	isSet bool
}

func (v NullableUtilization) Get() *Utilization {
	return v.value
}

func (v *NullableUtilization) Set(val *Utilization) {
	v.value = val
	v.isSet = true
}

func (v NullableUtilization) IsSet() bool {
	return v.isSet
}

func (v *NullableUtilization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUtilization(val *Utilization) *NullableUtilization {
	return &NullableUtilization{value: val, isSet: true}
}

func (v NullableUtilization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUtilization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
