/*
Billing API

Automate your infrastructure billing with the Bare Metal Cloud Billing API. Reserve your server instances to ensure guaranteed resource availability for 12, 24, and 36 months. Retrieve your server’s rated usage for a given period and enable or disable auto-renewals.<br> <br> <span class='pnap-api-knowledge-base-link'> Knowledge base articles to help you can be found <a href='https://phoenixnap.com/kb/phoenixnap-bare-metal-cloud-billing-models' target='_blank'>here</a> </span><br> <br> <b>All URLs are relative to (https://api.phoenixnap.com/billing/v1/)</b>

API version: 0.1
Contact: support@phoenixnap.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billingapi

import (
	"encoding/json"
	"fmt"
)

// QuantityUnitEnum The quantity unit.
type QuantityUnitEnum string

// List of QuantityUnitEnum
const (
	QUANTITYUNITENUM_TB    QuantityUnitEnum = "TB"
	QUANTITYUNITENUM_COUNT QuantityUnitEnum = "COUNT"
)

// All allowed values of QuantityUnitEnum enum
var AllowedQuantityUnitEnumEnumValues = []QuantityUnitEnum{
	"TB",
	"COUNT",
}

func (v *QuantityUnitEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := QuantityUnitEnum(value)
	for _, existing := range AllowedQuantityUnitEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid QuantityUnitEnum", value)
}

// NewQuantityUnitEnumFromValue returns a pointer to a valid QuantityUnitEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewQuantityUnitEnumFromValue(v string) (*QuantityUnitEnum, error) {
	ev := QuantityUnitEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for QuantityUnitEnum: valid values are %v", v, AllowedQuantityUnitEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v QuantityUnitEnum) IsValid() bool {
	for _, existing := range AllowedQuantityUnitEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to QuantityUnitEnum value
func (v QuantityUnitEnum) Ptr() *QuantityUnitEnum {
	return &v
}

type NullableQuantityUnitEnum struct {
	value *QuantityUnitEnum
	isSet bool
}

func (v NullableQuantityUnitEnum) Get() *QuantityUnitEnum {
	return v.value
}

func (v *NullableQuantityUnitEnum) Set(val *QuantityUnitEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableQuantityUnitEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableQuantityUnitEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuantityUnitEnum(val *QuantityUnitEnum) *NullableQuantityUnitEnum {
	return &NullableQuantityUnitEnum{value: val, isSet: true}
}

func (v NullableQuantityUnitEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuantityUnitEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
