/*
Billing API

Automate your infrastructure billing with the Bare Metal Cloud Billing API. Reserve your server instances to ensure guaranteed resource availability for 12, 24, and 36 months. Retrieve your server’s rated usage for a given period and enable or disable auto-renewals.<br> <br> <span class='pnap-api-knowledge-base-link'> Knowledge base articles to help you can be found <a href='https://phoenixnap.com/kb/phoenixnap-bare-metal-cloud-billing-models' target='_blank'>here</a> </span><br> <br> <b>All URLs are relative to (https://api.phoenixnap.com/billing/v1/)</b> 

API version: 0.1
Contact: support@phoenixnap.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billingapi

import (
	"encoding/json"
)

// BandwidthRecordAllOf Bandwidth usage record.
type BandwidthRecordAllOf struct {
	Metadata BandwidthDetails `json:"metadata"`
}

// NewBandwidthRecordAllOf instantiates a new BandwidthRecordAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBandwidthRecordAllOf(metadata BandwidthDetails) *BandwidthRecordAllOf {
	this := BandwidthRecordAllOf{}
	this.Metadata = metadata
	return &this
}

// NewBandwidthRecordAllOfWithDefaults instantiates a new BandwidthRecordAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBandwidthRecordAllOfWithDefaults() *BandwidthRecordAllOf {
	this := BandwidthRecordAllOf{}
	return &this
}

// GetMetadata returns the Metadata field value
func (o *BandwidthRecordAllOf) GetMetadata() BandwidthDetails {
	if o == nil {
		var ret BandwidthDetails
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *BandwidthRecordAllOf) GetMetadataOk() (*BandwidthDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *BandwidthRecordAllOf) SetMetadata(v BandwidthDetails) {
	o.Metadata = v
}

func (o BandwidthRecordAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["metadata"] = o.Metadata
	}
	return json.Marshal(toSerialize)
}

type NullableBandwidthRecordAllOf struct {
	value *BandwidthRecordAllOf
	isSet bool
}

func (v NullableBandwidthRecordAllOf) Get() *BandwidthRecordAllOf {
	return v.value
}

func (v *NullableBandwidthRecordAllOf) Set(val *BandwidthRecordAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableBandwidthRecordAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableBandwidthRecordAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBandwidthRecordAllOf(val *BandwidthRecordAllOf) *NullableBandwidthRecordAllOf {
	return &NullableBandwidthRecordAllOf{value: val, isSet: true}
}

func (v NullableBandwidthRecordAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBandwidthRecordAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


