openapi: 3.0.2
info:
  contact:
    email: support@phoenixnap.com
    name: PhoenixNAP Team
    url: https://phoenixnap.com/
  description: "Create, power off, power on, reset, reboot, or shut down your server\
    \ with the Bare Metal Cloud API. \nDeprovision servers, get or edit SSH key details,\
    \ assign public IPs, assign servers to networks and a lot more. \nManage your\
    \ infrastructure more efficiently using just a few simple API calls.<br>\n<br>\n\
    <span class='pnap-api-knowledge-base-link'>\nKnowledge base articles to help you\
    \ can be found\n<a href='https://phoenixnap.com/kb/how-to-deploy-bare-metal-cloud-server'\
    \ target='_blank'>here</a>\n</span><br>\n<br>\n<b>All URLs are relative to (https://api.phoenixnap.com/bmc/v1/)</b>\n"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://phoenixnap.com/infrastructure-solutions/legal-it/privacy-shield-compliant-privacy-policy
  title: Bare Metal Cloud API
  version: "0.1"
servers:
- url: https://api.phoenixnap.com/bmc/v1
security:
- OAuth2:
  - bmc
  - bmc.read
tags:
- description: Server operations
  name: Servers
- description: Quota operations
  name: Quotas
- description: SSH Key operations
  name: SSH Keys
paths:
  /servers:
    get:
      description: List all servers owned by account.
      operationId: serversGet
      security:
      - OAuth2:
        - bmc.read
      summary: List servers.
      tags:
      - Servers
    post:
      description: Create (request) new server for account. Server DNS will be configured
        to access Google's public DNS at 8.8.8.8 .
      operationId: serversPost
      security:
      - OAuth2:
        - bmc
      summary: Create new server.
      tags:
      - Servers
  /servers/{serverId}:
    delete:
      deprecated: true
      description: "Deprovision specific server. Any IP blocks assigned to this server\
        \ will also be relinquished and deleted. Deprecated: see /servers/{serverId}/actions/deprovision"
      operationId: serversServerIdDelete
      security:
      - OAuth2:
        - bmc
      summary: Delete server.
      tags:
      - Servers
    get:
      description: Get server properties.
      operationId: serversServerIdGet
      security:
      - OAuth2:
        - bmc.read
      summary: Get server.
      tags:
      - Servers
    patch:
      description: Any changes to the hostname or description using the BMC API will
        reflect solely in the BMC API and portal. The changes are intended to keep
        the BMC data up to date with your server. We do not have access to your server's
        settings. Local changes to the server's hostname will not be reflected in
        the API or portal.
      operationId: serversServerIdPatch
      security:
      - OAuth2:
        - bmc
      summary: Patch a Server.
      tags:
      - Servers
  /servers/{serverId}/network-configuration/ip-block-configurations/ip-blocks:
    post:
      description: Adds an IP block to this server. <b>No actual configuration is
        performed on the operating system.</b> BMC configures exclusively the networking
        devices in the datacenter infrastructure. Manual network configuration changes
        in the operating system of this server are required. Knowledge base article
        to help you can be found <a href='https://phoenixnap.com/kb/configure-server-with-public-ip-block#ftoc-heading-2'
        target='_blank'>here</a>.
      operationId: serversServerIdIpBlocksPost
      security:
      - OAuth2:
        - bmc
      summary: Assign IP Block to Server.
      tags:
      - Servers
  /servers/{serverId}/network-configuration/ip-block-configurations/ip-blocks/{ipBlockId}:
    delete:
      description: Removes the IP block from the server. <b>No actual configuration
        is performed on the operating system.</b> BMC configures exclusively the networking
        devices in the datacenter infrastructure. Manual network configuration changes
        in the operating system of this server are required. <b>This is an advanced
        network action that can make your server completely unavailable over any network.
        Make sure this server is reachable over remote console for guaranteed access
        in case of misconfiguration.</b>
      operationId: serversServerIdIpBlocksIpBlockIdDelete
      security:
      - OAuth2:
        - bmc
      summary: Unassign IP Block from Server.
      tags:
      - Servers
  /servers/{serverId}/network-configuration/private-network-configuration/private-networks:
    post:
      description: Adds the server to a private network. <b>No actual configuration
        is performed on the operating system.</b> BMC configures exclusively the networking
        devices in the datacenter infrastructure. Manual network configuration changes
        in the operating system of this server are required. Knowledge base article
        to help you can be found <a href='https://phoenixnap.com/kb/configure-bmc-server-after-adding-to-network#ftoc-heading-3'
        target='_blank'>here</a>.
      operationId: serversServerIdPrivateNetworksPost
      security:
      - OAuth2:
        - bmc
      summary: Adds the server to a private network.
      tags:
      - Servers
  /servers/{serverId}/network-configuration/private-network-configuration/private-networks/{privateNetworkId}:
    delete:
      description: Removes the server from private network. <b>No actual configuration
        is performed on the operating system.</b> BMC configures exclusively the networking
        devices in the datacenter infrastructure. Manual network configuration changes
        in the operating system of this server are required. <b>This is an advanced
        network action that can make your server completely unavailable over any network.
        Make sure this server is reachable over remote console for guaranteed access
        in case of misconfiguration.</b>
      operationId: deletePrivateNetwork
      security:
      - OAuth2:
        - bmc
      summary: Removes the server from private network.
      tags:
      - Servers
    patch:
      description: IP address changes intended to keep the BMC data up to date with
        server's operating system. We do not have access to the server's operating
        system and therefore manual configuration is required to apply the changes
        on the host. Knowledge base article to help you can be found <a href='https://phoenixnap.com/kb/bmc-server-management-via-api#ftoc-heading-6'
        target='_blank'>here</a>
      operationId: serversServerIdPrivateNetworksPatch
      security:
      - OAuth2:
        - bmc
      summary: Updates the server's private network's IP addresses
      tags:
      - Servers
  /servers/{serverId}/network-configuration/public-network-configuration/public-networks:
    post:
      description: Adds the server to a Public Network. <b>No actual configuration
        is performed on the operating system.</b> BMC configures exclusively the networking
        devices in the datacenter infrastructure. Manual network configuration changes
        in the operating system of this server are required. Knowledge base article
        to help you can be found <a href='https://phoenixnap.com/kb/configure-bmc-server-after-adding-to-network#ftoc-heading-3'
        target='_blank'>here</a>.
      operationId: serversServerIdPublicNetworksPost
      security:
      - OAuth2:
        - bmc
      summary: Adds the server to a Public Network.
      tags:
      - Servers
  /servers/{serverId}/network-configuration/public-network-configuration/public-networks/{publicNetworkId}:
    delete:
      description: Removes the server from the Public Network. <b>No actual configuration
        is performed on the operating system.</b> BMC configures exclusively the networking
        devices in the datacenter infrastructure. Manual network configuration changes
        in the operating system of this server are required. <b>This is an advanced
        network action that can make your server completely unavailable over any network.
        Make sure this server is reachable over remote console for guaranteed access
        in case of misconfiguration.</b>
      operationId: serversServerIdPublicNetworksDelete
      security:
      - OAuth2:
        - bmc
      summary: Removes the server from the Public Network
      tags:
      - Servers
    patch:
      description: IP address changes intended to keep the BMC data up to date with
        server's operating system. We do not have access to the server's operating
        system and therefore manual configuration is required to apply the changes
        on the host. Knowledge base article to help you can be found <a href='https://phoenixnap.com/kb/bmc-server-management-via-api#ftoc-heading-6'
        target='_blank'>here</a>
      operationId: serversServerIdPublicNetworksPatch
      security:
      - OAuth2:
        - bmc
      summary: Updates the server's public network's IP addresses.
      tags:
      - Servers
  /servers/{serverId}/tags:
    put:
      description: Overwrites tags assigned for Server and unassigns any tags not
        part of the request.
      operationId: serversServerIdTagsPut
      security:
      - OAuth2:
        - bmc
      summary: Overwrite tags assigned for Server.
      tags:
      - Servers
  /servers/{serverId}/actions/deprovision:
    post:
      description: Deprovision the server. Supports advanced deprovision configuration.
      operationId: serversServerIdActionsDeprovisionPost
      security:
      - OAuth2:
        - bmc
      summary: Deprovision a server.
      tags:
      - Servers
  /servers/{serverId}/actions/power-on:
    post:
      description: Power on specific server.
      operationId: serversServerIdActionsPowerOnPost
      security:
      - OAuth2:
        - bmc
      summary: Power on server.
      tags:
      - Servers
  /servers/{serverId}/actions/power-off:
    post:
      description: Power off specific server.
      operationId: serversServerIdActionsPowerOffPost
      security:
      - OAuth2:
        - bmc
      summary: Power off server.
      tags:
      - Servers
  /servers/{serverId}/actions/reboot:
    post:
      description: Reboot specific server.
      operationId: serversServerIdActionsRebootPost
      security:
      - OAuth2:
        - bmc
      summary: Reboot server.
      tags:
      - Servers
  /servers/{serverId}/actions/shutdown:
    post:
      description: Shut down specific server.
      operationId: serversServerIdActionsShutdownPost
      security:
      - OAuth2:
        - bmc
      summary: Shutdown server.
      tags:
      - Servers
  /servers/{serverId}/actions/reset:
    post:
      deprecated: true
      description: "Deprecated: Reset specific server. Reset only supports network\
        \ configurations of type 'private network' or 'IP blocks'. As an alternative,\
        \ the suggested action is to deprovision the server and provision a new one\
        \ with the same configuration."
      operationId: serversServerIdActionsResetPost
      security:
      - OAuth2:
        - bmc
      summary: Reset server.
      tags:
      - Servers
  /servers/{serverId}/actions/reserve:
    post:
      description: Reserve specific server.
      operationId: serversServerIdActionsReservePost
      security:
      - OAuth2:
        - bmc
      summary: Reserve server.
      tags:
      - Servers
  /ssh-keys:
    get:
      description: List all SSH Keys.
      operationId: sshKeysGet
      security:
      - OAuth2:
        - bmc.read
      summary: List SSH Keys.
      tags:
      - SSH Keys
    post:
      description: Create an SSH Key. SSH Keys created can be used for server creation
        and reset functionality.
      operationId: sshKeysPost
      security:
      - OAuth2:
        - bmc
      summary: Create SSH Key.
      tags:
      - SSH Keys
  /ssh-keys/{sshKeyId}:
    delete:
      description: Delete an SSH Key.
      operationId: sshKeysSshKeyIdDelete
      security:
      - OAuth2:
        - bmc
      summary: Delete SSH Key.
      tags:
      - SSH Keys
    get:
      description: Get SSH Key details.
      operationId: sshKeysSshKeyIdGet
      security:
      - OAuth2:
        - bmc.read
      summary: Get SSH Key.
      tags:
      - SSH Keys
    put:
      description: Edit SSH Key details.
      operationId: sshKeysSshKeyIdPut
      security:
      - OAuth2:
        - bmc
      summary: Edit SSH Key.
      tags:
      - SSH Keys
  /quotas:
    get:
      description: Get account quota details.
      operationId: quotasGet
      security:
      - OAuth2:
        - bmc.read
      summary: List quotas
      tags:
      - Quotas
  /quotas/{quotaId}:
    get:
      description: Get account quota details.
      operationId: quotasQuotaIdGet
      security:
      - OAuth2:
        - bmc.read
      summary: Get a quota.
      tags:
      - Quotas
  /quotas/{quotaId}/actions/request-edit:
    post:
      description: Sends a request to edit the limit of a quota.
      operationId: quotasQuotaIdActionsRequestEditPost
      security:
      - OAuth2:
        - bmc
      summary: Request quota limit change.
      tags:
      - Quotas
components:
  securitySchemes:
    OAuth2:
      flows:
        clientCredentials:
          scopes:
            bmc: Grants full access to bmc-api.
            bmc.read: Grants read only access to bmc-api.
          tokenUrl: https://auth.phoenixnap.com/auth/realms/BMC/protocol/openid-connect/token
      type: oauth2
