/*
Network Storage API

Create, list, edit, and delete storage networks with the Network Storage API. Use storage networks to expand storage capacity on a private network. <br> <span class='pnap-api-knowledge-base-link'> Knowledge base articles to help you can be found <a href='https://phoenixnap.com/kb/bare-metal-cloud-storage' target='_blank'>here</a> </span> <br> <b>All URLs are relative to (https://api.phoenixnap.com/network-storage/v1/)</b>

API version: 1.0
Contact: support@phoenixnap.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package networkstorageapi

import (
	"encoding/json"
)

// PermissionsCreate Update permissions for a volume.
type PermissionsCreate struct {
	Nfs *NfsPermissionsCreate `json:"nfs,omitempty"`
}

// NewPermissionsCreate instantiates a new PermissionsCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionsCreate() *PermissionsCreate {
	this := PermissionsCreate{}
	return &this
}

// NewPermissionsCreateWithDefaults instantiates a new PermissionsCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionsCreateWithDefaults() *PermissionsCreate {
	this := PermissionsCreate{}
	return &this
}

// GetNfs returns the Nfs field value if set, zero value otherwise.
func (o *PermissionsCreate) GetNfs() NfsPermissionsCreate {
	if o == nil || o.Nfs == nil {
		var ret NfsPermissionsCreate
		return ret
	}
	return *o.Nfs
}

// GetNfsOk returns a tuple with the Nfs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionsCreate) GetNfsOk() (*NfsPermissionsCreate, bool) {
	if o == nil || o.Nfs == nil {
		return nil, false
	}
	return o.Nfs, true
}

// HasNfs returns a boolean if a field has been set.
func (o *PermissionsCreate) HasNfs() bool {
	if o != nil && o.Nfs != nil {
		return true
	}

	return false
}

// SetNfs gets a reference to the given NfsPermissionsCreate and assigns it to the Nfs field.
func (o *PermissionsCreate) SetNfs(v NfsPermissionsCreate) {
	o.Nfs = &v
}

func (o PermissionsCreate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Nfs != nil {
		toSerialize["nfs"] = o.Nfs
	}
	return json.Marshal(toSerialize)
}

type NullablePermissionsCreate struct {
	value *PermissionsCreate
	isSet bool
}

func (v NullablePermissionsCreate) Get() *PermissionsCreate {
	return v.value
}

func (v *NullablePermissionsCreate) Set(val *PermissionsCreate) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionsCreate) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionsCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionsCreate(val *PermissionsCreate) *NullablePermissionsCreate {
	return &NullablePermissionsCreate{value: val, isSet: true}
}

func (v NullablePermissionsCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionsCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
