openapi: 3.0.2
info:
  contact:
    email: support@phoenixnap.com
    name: PhoenixNAP Team
    url: https://phoenixnap.com/
  description: "Automate your infrastructure billing with the Bare Metal Cloud Billing\
    \ API. Reserve your server instances to\nensure guaranteed resource availability\
    \ for 12, 24, and 36 months. Retrieve your server’s rated usage for a\ngiven period\
    \ and enable or disable auto-renewals.<br>\n<br>\n<span class='pnap-api-knowledge-base-link'>\n\
    Knowledge base articles to help you can be found\n<a href='https://phoenixnap.com/kb/phoenixnap-bare-metal-cloud-billing-models'\
    \ target='_blank'>here</a>\n</span><br>\n<br>\n<b>All URLs are relative to (https://api.phoenixnap.com/billing/v1/)</b>\n"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://phoenixnap.com/infrastructure-solutions/legal-it/privacy-shield-compliant-privacy-policy
  title: Billing API
  version: "0.1"
servers:
- url: https://api.phoenixnap.com/billing/v1
security:
- OAuth2:
  - bmc
  - bmc.read
tags:
- description: Rated Usage operations
  name: Rated Usage
- description: Product operations
  name: Products
- description: Reservation operations
  name: Reservations
- description: Account Billing Configuration operations
  name: Billing Configurations
paths:
  /rated-usage:
    get:
      description: Retrieves all rated usage for given time period. The information
        is presented as a list of rated usage records. Every record corresponds to
        a charge. All date & times are in UTC.
      operationId: ratedUsageGet
      security:
      - OAuth2:
        - bmc.read
      summary: List the rated usage.
      tags:
      - Rated Usage
  /rated-usage/month-to-date:
    get:
      description: Retrieves all rated usage for the current calendar month. The information
        is presented as a list of rated usage records. Every record corresponds to
        a charge. All date & times are in UTC.
      operationId: ratedUsageMonthToDateGet
      security:
      - OAuth2:
        - bmc.read
      summary: List the rated usage records for the current calendar month.
      tags:
      - Rated Usage
  /products:
    get:
      description: Retrieves all Products.
      operationId: productsGet
      security:
      - OAuth2:
        - bmc.read
      summary: List all Products.
      tags:
      - Products
  /reservations:
    get:
      description: Retrieves all reservations associated with the authenticated account.
        All date & times are in UTC.
      operationId: reservationsGet
      security:
      - OAuth2:
        - bmc.read
      summary: List all Reservations.
      tags:
      - Reservations
    post:
      description: Creates new package reservation for authenticated account.
      operationId: reservationsPost
      security:
      - OAuth2:
        - bmc
      summary: Create a reservation.
      tags:
      - Reservations
  /reservations/{reservationId}:
    get:
      description: Retrieves the reservations with the specified identifier. All date
        & times are in UTC.
      operationId: reservationsReservationIdGet
      security:
      - OAuth2:
        - bmc.read
      summary: Get a reservation.
      tags:
      - Reservations
  /reservations/{reservationId}/actions/auto-renew/disable:
    description: Disable auto-renewal for reservation by the reservation id.
    post:
      description: Disable auto-renewal for reservation by reservation id.
      operationId: reservationsReservationIdActionsAutoRenewDisablePost
      security:
      - OAuth2:
        - bmc
      summary: Disable auto-renewal for reservation by id.
      tags:
      - Reservations
  /reservations/{reservationId}/actions/auto-renew/enable:
    description: Enable auto-renewal for reservation by the reservation id.
    post:
      description: Enable auto-renewal for unexpired reservation by reservation id.
      operationId: reservationsReservationIdActionsAutoRenewEnablePost
      security:
      - OAuth2:
        - bmc
      summary: Enable auto-renewal for unexpired reservation by reservation id.
      tags:
      - Reservations
  /reservations/{reservationId}/actions/convert:
    description: Convert reservation pricing model.
    post:
      description: Convert reservation pricing model by reservation id.
      operationId: reservationsReservationIdActionsConvertPost
      security:
      - OAuth2:
        - bmc
      summary: Convert reservation pricing model by reservation ID.
      tags:
      - Reservations
  /account-billing-configurations/me:
    description: Retrieves billing configuration associated with the authenticated
      account.
    get:
      description: Retrieves billing configuration associated with the authenticated
        account.
      operationId: accountBillingConfigurationMeGet
      security:
      - OAuth2:
        - bmc.read
      summary: Retrieves billing configuration associated with the authenticated account.
      tags:
      - Billing Configurations
  /product-availability:
    description: Retrieves all product availabilities.
    get:
      description: Retrieves the list of product availability details.
      operationId: productAvailabilityGet
      security:
      - OAuth2:
        - bmc.read
      summary: List all Product availabilities.
      tags:
      - Products
components:
  securitySchemes:
    OAuth2:
      flows:
        clientCredentials:
          scopes:
            bmc: Grants full access to bmc-api.
            bmc.read: Grants read only access to bmc-api.
          tokenUrl: https://auth.phoenixnap.com/auth/realms/BMC/protocol/openid-connect/token
      type: oauth2
