/*
Invoicing API

List, fetch and pay invoices with the Invoicing API.

API version: 1.0
Contact: support@phoenixnap.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicingapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PaginatedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedResponse{}

// PaginatedResponse struct for PaginatedResponse
type PaginatedResponse struct {
	// Maximum number of items in the page (actual returned length can be less).
	Limit int32 `json:"limit"`
	// The number of returned items skipped.
	Offset int32 `json:"offset"`
	// The total number of records available for retrieval.
	Total int32 `json:"total"`
}

type _PaginatedResponse PaginatedResponse

// NewPaginatedResponse instantiates a new PaginatedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedResponse(limit int32, offset int32, total int32) *PaginatedResponse {
	this := PaginatedResponse{}
	this.Limit = limit
	this.Offset = offset
	this.Total = total
	return &this
}

// NewPaginatedResponseWithDefaults instantiates a new PaginatedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedResponseWithDefaults() *PaginatedResponse {
	this := PaginatedResponse{}
	return &this
}

// GetLimit returns the Limit field value
func (o *PaginatedResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *PaginatedResponse) SetLimit(v int32) {
	o.Limit = v
}

// GetOffset returns the Offset field value
func (o *PaginatedResponse) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponse) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *PaginatedResponse) SetOffset(v int32) {
	o.Offset = v
}

// GetTotal returns the Total field value
func (o *PaginatedResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *PaginatedResponse) SetTotal(v int32) {
	o.Total = v
}

func (o PaginatedResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["limit"] = o.Limit
	toSerialize["offset"] = o.Offset
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *PaginatedResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"limit",
		"offset",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedResponse := _PaginatedResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedResponse)

	if err != nil {
		return err
	}

	*o = PaginatedResponse(varPaginatedResponse)

	return err
}

type NullablePaginatedResponse struct {
	value *PaginatedResponse
	isSet bool
}

func (v NullablePaginatedResponse) Get() *PaginatedResponse {
	return v.value
}

func (v *NullablePaginatedResponse) Set(val *PaginatedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedResponse(val *PaginatedResponse) *NullablePaginatedResponse {
	return &NullablePaginatedResponse{value: val, isSet: true}
}

func (v NullablePaginatedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
