openapi: 3.0.2
info:
  contact:
    email: support@phoenixnap.com
    name: PhoenixNAP Team
    url: https://phoenixnap.com/
  description: "Create, list, edit, and delete storage networks with the Network Storage\
    \ API. Use storage networks to expand storage capacity on a private network.\n\
    <br>\n<span class='pnap-api-knowledge-base-link'>\nKnowledge base articles to\
    \ help you can be found\n<a href='https://phoenixnap.com/kb/bare-metal-cloud-storage'\
    \ target='_blank'>here</a>\n</span>\n<br>\n<b>All URLs are relative to (https://api.phoenixnap.com/network-storage/v1/)</b>\n"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://phoenixnap.com/infrastructure-solutions/legal-it/privacy-shield-compliant-privacy-policy
  title: Network Storage API
  version: "1.0"
servers:
- url: https://api.phoenixnap.com/network-storage/v1
security:
- OAuth2:
  - networkstorage
  - networkstorage.read
tags:
- description: Storage Networks operations.
  name: Storage Networks
paths:
  /storage-networks:
    get:
      description: List all storage networks.
      operationId: storageNetworksGet
      security:
      - OAuth2:
        - networkstorage.read
      summary: List all storage networks.
      tags:
      - Storage Networks
    post:
      description: Create a storage network and volume.
      operationId: storageNetworksPost
      security:
      - OAuth2:
        - networkstorage
      summary: Create a storage network and volume.
      tags:
      - Storage Networks
  /storage-networks/{storageId}:
    delete:
      description: Delete a storage network and its volume. A storage network can
        only be removed if it's not in 'BUSY' state. Billing stops on storage network
        deletion.
      operationId: storageNetworksIdDelete
      security:
      - OAuth2:
        - networkstorage
      summary: Delete a storage network and its volume.
      tags:
      - Storage Networks
    get:
      description: Get storage network details.
      operationId: storageNetworksIdGet
      security:
      - OAuth2:
        - networkstorage.read
      summary: Get storage network details.
      tags:
      - Storage Networks
    patch:
      description: Update storage network details.
      operationId: storageNetworksIdPatch
      security:
      - OAuth2:
        - networkstorage
      summary: Update storage network details.
      tags:
      - Storage Networks
  /storage-networks/{storageId}/volumes:
    get:
      description: Display one or more volumes belonging to a storage network.
      operationId: storageNetworksStorageNetworkIdVolumesGet
      security:
      - OAuth2:
        - networkstorage.read
      summary: Display one or more volumes belonging to a storage network.
      tags:
      - Storage Networks
    post:
      description: Create a volume belonging to a storage network.
      operationId: storageNetworksStorageNetworkIdVolumesPost
      security:
      - OAuth2:
        - networkstorage
      summary: Create a volume belonging to a storage network.
      tags:
      - Storage Networks
  /storage-networks/{storageId}/volumes/{volumeId}:
    delete:
      description: Delete a Storage Network's Volume
      operationId: storageNetworksStorageNetworkIdVolumesVolumeIdDelete
      security:
      - OAuth2:
        - networkstorage
      summary: Delete a Storage Network's Volume
      tags:
      - Storage Networks
    get:
      description: Get a storage network's volume details.
      operationId: storageNetworksStorageNetworkIdVolumesVolumeIdGet
      security:
      - OAuth2:
        - networkstorage.read
      summary: Get a storage network's volume details.
      tags:
      - Storage Networks
    patch:
      description: Update a storage network's volume details.
      operationId: storageNetworksStorageNetworkIdVolumesVolumeIdPatch
      security:
      - OAuth2:
        - networkstorage
      summary: Update a storage network's volume details.
      tags:
      - Storage Networks
  /storage-networks/{storageId}/volumes/{volumeId}/tags:
    put:
      description: Overwrites tags assigned for the volume.
      operationId: storageNetworksStorageNetworkIdVolumesVolumeIdTagsPut
      security:
      - OAuth2:
        - networkstorage
      summary: Overwrites tags assigned for the volume.
      tags:
      - Storage Networks
components:
  securitySchemes:
    OAuth2:
      flows:
        clientCredentials:
          scopes:
            networkstorage: Grants full access to Network Storage API.
            networkstorage.read: Grants read only access to Network Storage API.
          tokenUrl: https://auth.phoenixnap.com/auth/realms/BMC/protocol/openid-connect/token
      type: oauth2
