openapi: 3.0.2
info:
  contact:
    email: support@phoenixnap.com
    name: PhoenixNAP Team
    url: https://phoenixnap.com/
  description: "Create, list, edit and delete public/private networks with the Network\
    \ API. Use public networks to place multiple \nservers on the same network or\
    \ VLAN. Assign new servers with IP addresses from the same CIDR range. Use private\
    \ \nnetworks to avoid unnecessary egress data charges. Model your networks according\
    \ to your business needs.<br>\n<br>\n<span class='pnap-api-knowledge-base-link'>\n\
    Helpful knowledge base articles are available for \n<a href='https://phoenixnap.com/kb/bmc-server-management-via-api#multi-private-backend-network-api'\
    \ target='_blank'>multi-private backend networks</a>\nand <a href='https://phoenixnap.com/kb/bmc-server-management-via-api#ftoc-heading-15'\
    \ target='_blank'>public networks</a>.\n</span><br>\n<br>\n<b>All URLs are relative\
    \ to (https://api.phoenixnap.com/networks/v1/)</b>\n"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://phoenixnap.com/infrastructure-solutions/legal-it/privacy-shield-compliant-privacy-policy
  title: Networks API
  version: "1.0"
servers:
- url: https://api.phoenixnap.com/networks/v1
security:
- OAuth2:
  - bmc
  - bmc.read
tags:
- description: Private Network operations
  name: Private Networks
- description: Public networks operations
  name: Public Networks
paths:
  /private-networks:
    get:
      description: List all Private Networks owned by account.
      operationId: privateNetworksGet
      security:
      - OAuth2:
        - bmc.read
      summary: List Private Networks.
      tags:
      - Private Networks
    post:
      description: Create a Private Network.
      operationId: privateNetworksPost
      security:
      - OAuth2:
        - bmc
      summary: Create a Private Network.
      tags:
      - Private Networks
  /private-networks/{privateNetworkId}:
    delete:
      description: Delete Private Network.
      operationId: privateNetworksNetworkIdDelete
      security:
      - OAuth2:
        - bmc
      summary: Delete a Private Network.
      tags:
      - Private Networks
    get:
      description: Retrieve Private Network Details.
      operationId: privateNetworksNetworkIdGet
      security:
      - OAuth2:
        - bmc.read
      summary: Get a Private Network.
      tags:
      - Private Networks
    put:
      description: Update Private Network Details.
      operationId: privateNetworksNetworkIdPut
      security:
      - OAuth2:
        - bmc
      summary: Update a Private Network.
      tags:
      - Private Networks
  /public-networks:
    get:
      description: List all Public Networks owned by account.
      operationId: publicNetworksGet
      security:
      - OAuth2:
        - bmc.read
      summary: List Public Networks.
      tags:
      - Public Networks
    post:
      description: Create a public network.
      operationId: publicNetworksPost
      security:
      - OAuth2:
        - bmc
      summary: Create a public network.
      tags:
      - Public Networks
  /public-networks/{publicNetworkId}:
    delete:
      description: Delete Public Network. The request is accepted only if no resources
        are members of this network. The IP Block(s) will be freed and can be re-used
        in the future.
      operationId: publicNetworksNetworkIdDelete
      security:
      - OAuth2:
        - bmc
      summary: Delete a Public Network.
      tags:
      - Public Networks
    get:
      description: Retrieve Public Network Details.
      operationId: publicNetworksNetworkIdGet
      security:
      - OAuth2:
        - bmc.read
      summary: Get a Public Network.
      tags:
      - Public Networks
    patch:
      description: Update Public Network's Details.
      operationId: publicNetworksNetworkIdPatch
      security:
      - OAuth2:
        - bmc
      summary: Update Public Network's Details.
      tags:
      - Public Networks
  /public-networks/{publicNetworkId}/ip-blocks:
    post:
      description: Adds an IP block to this public network.
      operationId: publicNetworksNetworkIdIpBlocksPost
      security:
      - OAuth2:
        - bmc
      summary: Adds an IP block to this public network.
      tags:
      - Public Networks
  /public-networks/{publicNetworkId}/ip-blocks/{ipBlockId}:
    delete:
      description: Removes the IP Block from the Public Network. The result of this
        is that any traffic addressed to any IP within the block will not be routed
        to this network anymore. Please ensure that no resource members within this
        network have any IPs assigned from the IP Block being removed.
      operationId: publicNetworksNetworkIdIpBlocksIpBlockIdDelete
      security:
      - OAuth2:
        - bmc
      summary: Removes the IP Block from the Public Network.
      tags:
      - Public Networks
components:
  securitySchemes:
    OAuth2:
      flows:
        clientCredentials:
          scopes:
            bmc: Grants full access to bmc-api.
            bmc.read: Grants read only access to bmc-api.
          tokenUrl: https://auth.phoenixnap.com/auth/realms/BMC/protocol/openid-connect/token
      type: oauth2
