openapi: 3.0.3
info:
  title: Audit Log API
  description: |
    The Audit Logs API lets you read audit log entries and track API calls or activities in the Bare Metal Cloud Portal.<br>
    <br>
    <span class='pnap-api-knowledge-base-link'>
    Knowledge base articles to help you can be found
    <a href='https://phoenixnap.com/kb/bmc-server-management-via-api#audit-log-api' target='_blank'>here</a>
    </span><br>
    <br>
    <b>All URLs are relative to (https://api.phoenixnap.com/audit/v1/)</b>
  termsOfService: https://phoenixnap.com/infrastructure-solutions/legal-it/privacy-shield-compliant-privacy-policy
  version: '1.0'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: PhoenixNAP Team
    email: support@phoenixnap.com
    url: https://phoenixnap.com/
security:
  - OAuth2:
      - audit.read
servers:
  - url: https://api.phoenixnap.com/audit/v1
tags:
  - name: Events
    description: Event operations
paths:
  /events:
    get:
      tags:
        - Events
      security:
        - OAuth2:
            - audit.read
      description: Retrieves the event logs for given time period. All date & times are in UTC.
      summary: List event logs.
      operationId: eventsGet
      parameters:
        - in: query
          name: from
          description: From the date and time (inclusive) to filter event log records by.
          required: false
          schema:
            type: string
            format: date-time
          example: '2021-04-27T16:24:57.123Z'
        - in: query
          name: to
          description: To the date and time (inclusive) to filter event log records by.
          required: false
          schema:
            type: string
            format: date-time
          example: '2021-04-29T16:24:57.123Z'
        - in: query
          name: limit
          required: false
          description: Limit the number of records returned.
          schema:
            type: integer
          example: 10
        - in: query
          name: order
          required: false
          description: Ordering of the event's time. SortBy can be introduced later on.
          schema:
            type: string
            enum:
              - ASC
              - DESC
            default: ASC
        - in: query
          name: username
          description: The username that did the actions.
          required: false
          schema:
            type: string
          example: johnd@phoenixnap.com
        - in: query
          name: verb
          description: The HTTP verb corresponding to the action.
          required: false
          schema:
            type: string
            enum:
              - POST
              - PUT
              - PATCH
              - DELETE
        - in: query
          name: uri
          description: The request uri.
          required: false
          schema:
            type: string
          example: /ams/v1/clients/12345
      responses:
        '200':
          description: The list of events recorded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '206':
          description: The truncated list of events recorded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.phoenixnap.com/auth/realms/BMC/protocol/openid-connect/token
          scopes:
            audit.read: Grants read only access to audit-log-api.
  schemas:
    UserInfo:
      type: object
      description: Details related to the user / application performing this request
      required:
        - accountId
        - username
      properties:
        accountId:
          description: The BMC account ID
          type: string
          example: 1234dfgdsf
        clientId:
          description: The client ID of the application
          type: string
          example: e9d335b1-3aa4-4760-9bad-2595c0449035
        username:
          description: The logged in user or owner of the client application
          type: string
          example: johnd@phoenixnap.com
    Event:
      type: object
      description: The event log.
      required:
        - timestamp
        - userInfo
      properties:
        name:
          description: The name of the event.
          type: string
          example: API.CreateServer
        timestamp:
          description: The UTC time the event initiated.
          type: string
          format: date-time
          example: 2020-03-19T16:39.123Z
        userInfo:
          $ref: '#/components/schemas/UserInfo'
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          readOnly: true
          description: The description detailing the cause of the error code.
        validationErrors:
          type: array
          items:
            type: string
          readOnly: true
          description: Validation errors, if any.
  responses:
    BadRequest:
      description: The request failed due to wrong data. Please check the provided parameters and try again.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: The request failed due to invalid credentials. Please check the provided credentials and try again.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: The request failed since this resource cannot be accessed by the provided credentials.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: The server encountered an unexpected condition that prevented it from fulfilling the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
