openapi: 3.0.2
info:
  title: Billing API
  description: |
    Automate your infrastructure billing with the Bare Metal Cloud Billing API. Reserve your server instances to
    ensure guaranteed resource availability for 12, 24, and 36 months. Retrieve your server’s rated usage for a
    given period and enable or disable auto-renewals.<br>
    <br>
    <span class='pnap-api-knowledge-base-link'>
    Knowledge base articles to help you can be found
    <a href='https://phoenixnap.com/kb/phoenixnap-bare-metal-cloud-billing-models' target='_blank'>here</a>
    </span><br>
    <br>
    <b>All URLs are relative to (https://api.phoenixnap.com/billing/v1/)</b>
  termsOfService: https://phoenixnap.com/infrastructure-solutions/legal-it/privacy-shield-compliant-privacy-policy
  version: '0.1'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: PhoenixNAP Team
    email: support@phoenixnap.com
    url: https://phoenixnap.com/
servers:
  - url: https://api.phoenixnap.com/billing/v1
security:
  - OAuth2:
      - bmc
      - bmc.read
tags:
  - name: Rated Usage
    description: Rated Usage operations
  - name: Products
    description: Product operations
  - name: Reservations
    description: Reservation operations
  - name: Billing Configurations
    description: Account Billing Configuration operations
  - name: Product Availability
    description: Product availability operations
paths:
  /rated-usage:
    get:
      tags:
        - Rated Usage
      description: Retrieves all rated usage for given time period. The information is presented as a list of rated usage records. Every record corresponds to a charge. All date & times are in UTC.
      summary: List the rated usage.
      operationId: ratedUsageGet
      security:
        - OAuth2:
            - bmc.read
  /rated-usage/month-to-date:
    get:
      tags:
        - Rated Usage
      description: Retrieves all rated usage for the current calendar month. The information is presented as a list of rated usage records. Every record corresponds to a charge. All date & times are in UTC.
      summary: List the rated usage records for the current calendar month.
      operationId: ratedUsageMonthToDateGet
      security:
        - OAuth2:
            - bmc.read
  /products:
    get:
      tags:
        - Products
      description: Retrieves all Products.
      summary: List all Products.
      security:
        - OAuth2:
            - bmc.read
      operationId: productsGet
  /reservations:
    get:
      tags:
        - Reservations
      description: Retrieves all reservations associated with the authenticated account. All date & times are in UTC.
      summary: List all Reservations.
      operationId: reservationsGet
      security:
        - OAuth2:
            - bmc.read
    post:
      tags:
        - Reservations
      description: Creates new package reservation for authenticated account.
      summary: Create a reservation.
      operationId: reservationsPost
      security:
        - OAuth2:
            - bmc
  /reservations/{id}:
    get:
      tags:
        - Reservations
      description: Retrieves the reservations with the specified identifier. All date & times are in UTC.
      summary: Get a reservation.
      operationId: reservationsReservationIdGet
      security:
        - OAuth2:
            - bmc.read
  /reservations/{id}/actions/auto-renew/disable:
    description: Disable auto-renewal for reservation by the reservation id.
    post:
      tags:
        - Reservations
      summary: Disable auto-renewal for reservation by id.
      description: Disable auto-renewal for reservation by reservation id.
      operationId: reservationsReservationIdActionsAutoRenewDisablePost
      security:
        - OAuth2:
            - bmc
  /reservations/{id}/actions/auto-renew/enable:
    description: Enable auto-renewal for reservation by the reservation id.
    post:
      tags:
        - Reservations
      summary: Enable auto-renewal for unexpired reservation by reservation id.
      description: Enable auto-renewal for unexpired reservation by reservation id.
      operationId: reservationsReservationIdActionsAutoRenewEnablePost
      security:
        - OAuth2:
            - bmc
  /reservations/{id}/actions/convert:
    description: Convert reservation pricing model.
    post:
      tags:
        - Reservations
      description: Convert reservation pricing model by reservation id.
      summary: Convert reservation pricing model by reservation ID.
      operationId: reservationsReservationIdActionsConvertPost
      security:
        - OAuth2:
            - bmc
  /account-billing-configurations/me:
    description: Retrieves billing configuration associated with the authenticated account.
    get:
      tags:
        - Billing Configurations
      description: Retrieves billing configuration associated with the authenticated account.
      summary: Retrieves billing configuration associated with the authenticated account.
      operationId: accountBillingConfigurationMeGet
      security:
        - OAuth2:
            - bmc.read
  /product-availability:
    description: Retrieves all product availabilities.
    get:
      tags:
        - Product Availability
      summary: List all Product availabilities.
      description: Retrieves the list of product availability details.
      security:
        - OAuth2:
            - bmc.read
      operationId: productAvailabilityGet
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.phoenixnap.com/auth/realms/BMC/protocol/openid-connect/token
          scopes:
            bmc: Grants full access to bmc-api.
            bmc.read: Grants read only access to bmc-api.