openapi: 3.0.2
info:
  title: Bare Metal Cloud API
  description: |
    Create, power off, power on, reset, reboot, or shut down your server with the Bare Metal Cloud API. 
    Deprovision servers, get or edit SSH key details, assign public IPs, assign servers to networks and a lot more. 
    Manage your infrastructure more efficiently using just a few simple API calls.<br>
    <br>
    <span class='pnap-api-knowledge-base-link'>
    Knowledge base articles to help you can be found
    <a href='https://phoenixnap.com/kb/how-to-deploy-bare-metal-cloud-server' target='_blank'>here</a>
    </span><br>
    <br>
    <b>All URLs are relative to (https://api.phoenixnap.com/bmc/v1/)</b>
  termsOfService: https://phoenixnap.com/infrastructure-solutions/legal-it/privacy-shield-compliant-privacy-policy
  version: '0.1'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: PhoenixNAP Team
    email: support@phoenixnap.com
    url: https://phoenixnap.com/
servers:
  - url: https://api.phoenixnap.com/bmc/v1
security:
  - OAuth2:
      - bmc
      - bmc.read
tags:
  - name: Servers
    description: Server operations
  - name: Quotas
    description: Quota operations
  - name: SSH Keys
    description: SSH Key operations
paths:
  /servers:
    get:
      tags:
        - Servers
      description: List all servers owned by account.
      summary: List servers.
      operationId: serversGet
      security:
        - OAuth2:
            - bmc.read
    post:
      tags:
        - Servers
      description: Create (request) a new server for the account. Server DNS will be configured to access Google's public DNS at 8.8.8.8 . Note that the product availability API can be used prior to doing the provision request. Refer to https://developers.phoenixnap.com/docs/bmc-billing/1/routes/product-availability/get.
      summary: Create new server.
      operationId: serversPost
      security:
        - OAuth2:
            - bmc
  /servers/{serverId}:
    get:
      tags:
        - Servers
      description: Get server properties.
      summary: Get server.
      operationId: serversServerIdGet
      security:
        - OAuth2:
            - bmc.read
    patch:
      tags:
        - Servers
      description: Any changes to the hostname or description using the BMC API will reflect solely in the BMC API and portal. The changes are intended to keep the BMC data up to date with your server. We do not have access to your server's settings. Local changes to the server's hostname will not be reflected in the API or portal.
      summary: Patch a Server.
      operationId: serversServerIdPatch
      security:
        - OAuth2:
            - bmc
    delete:
      tags:
        - Servers
      description: 'Deprovision specific server. Any IP blocks assigned to this server will also be relinquished and deleted. Deprecated: see /servers/{serverId}/actions/deprovision'
      summary: Delete server.
      deprecated: true
      operationId: serversServerIdDelete
      security:
        - OAuth2:
            - bmc
  /servers/{serverId}/network-configuration/ip-block-configurations/ip-blocks:
    post:
      tags:
        - Servers
      description: Adds an IP block to this server. <b>No actual configuration is performed on the operating system.</b> BMC configures exclusively the networking devices in the datacenter infrastructure. Manual network configuration changes in the operating system of this server are required. Knowledge base article to help you can be found <a href='https://phoenixnap.com/kb/configure-server-with-public-ip-block#ftoc-heading-2' target='_blank'>here</a>.
      summary: Assign IP Block to Server.
      operationId: serversServerIdIpBlocksPost
      security:
        - OAuth2:
            - bmc
  /servers/{serverId}/network-configuration/ip-block-configurations/ip-blocks/{ipBlockId}:
    delete:
      tags:
        - Servers
      description: Removes the IP block from the server. <b>No actual configuration is performed on the operating system.</b> BMC configures exclusively the networking devices in the datacenter infrastructure. Manual network configuration changes in the operating system of this server are required. <b>This is an advanced network action that can make your server completely unavailable over any network. Make sure this server is reachable over remote console for guaranteed access in case of misconf[...]
      summary: Unassign IP Block from Server.
      operationId: serversServerIdIpBlocksIpBlockIdDelete
      security:
        - OAuth2:
            - bmc
  /servers/{serverId}/network-configuration/private-network-configuration/private-networks:
    post:
      tags:
        - Servers
      description: Adds the server to a private network. <b>No actual configuration is performed on the operating system.</b> BMC configures exclusively the networking devices in the datacenter infrastructure. Manual network configuration changes in the operating system of this server are required. Knowledge base article to help you can be found <a href='https://phoenixnap.com/kb/configure-bmc-server-after-adding-to-network#ftoc-heading-3' target='_blank'>here</a>.
      summary: Adds the server to a private network.
      operationId: serversServerIdPrivateNetworksPost
      security:
        - OAuth2:
            - bmc
  /servers/{serverId}/network-configuration/private-network-configuration/private-networks/{privateNetworkId}:
    patch:
      tags:
        - Servers
      description: IP address changes intended to keep the BMC data up to date with server's operating system. We do not have access to the server's operating system and therefore manual configuration is required to apply the changes on the host. Knowledge base article to help you can be found <a href='https://phoenixnap.com/kb/bmc-server-management-via-api#ftoc-heading-6' target='_blank'>here</a>
      summary: Updates the server's private network's IP addresses
      operationId: serversServerIdPrivateNetworksPatch
      security:
        - OAuth2:
            - bmc
    delete:
      tags:
        - Servers
      description: Removes the server from private network. <b>No actual configuration is performed on the operating system.</b> BMC configures exclusively the networking devices in the datacenter infrastructure. Manual network configuration changes in the operating system of this server are required. <b>This is an advanced network action that can make your server completely unavailable over any network. Make sure this server is reachable over remote console for guaranteed access in case of misc[...]
      summary: Removes the server from private network.
      security:
        - OAuth2:
            - bmc
      operationId: deletePrivateNetwork
  /servers/{serverId}/network-configuration/public-network-configuration/public-networks:
    post:
      tags:
        - Servers
      description: Adds the server to a Public Network. <b>No actual configuration is performed on the operating system.</b> BMC configures exclusively the networking devices in the datacenter infrastructure. Manual network configuration changes in the operating system of this server are required. Knowledge base article to help you can be found <a href='https://phoenixnap.com/kb/configure-bmc-server-after-adding-to-network#ftoc-heading-3' target='_blank'>here</a>.
      summary: Adds the server to a Public Network.
      operationId: serversServerIdPublicNetworksPost
      security:
        - OAuth2:
            - bmc
  /servers/{serverId}/network-configuration/public-network-configuration/public-networks/{publicNetworkId}:
    patch:
      tags:
        - Servers
      description: IP address changes intended to keep the BMC data up to date with server's operating system. We do not have access to the server's operating system and therefore manual configuration is required to apply the changes on the host. Knowledge base article to help you can be found <a href='https://phoenixnap.com/kb/bmc-server-management-via-api#ftoc-heading-6' target='_blank'>here</a>
      summary: Updates the server's public network's IP addresses.
      operationId: serversServerIdPublicNetworksPatch
      security:
        - OAuth2:
            - bmc
    delete:
      tags:
        - Servers
      description: Removes the server from the Public Network. <b>No actual configuration is performed on the operating system.</b> BMC configures exclusively the networking devices in the datacenter infrastructure. Manual network configuration changes in the operating system of this server are required. <b>This is an advanced network action that can make your server completely unavailable over any network. Make sure this server is reachable over remote console for guaranteed access in case of m[...]
      summary: Removes the server from the Public Network
      operationId: serversServerIdPublicNetworksDelete
      security:
        - OAuth2:
            - bmc
  /servers/{serverId}/tags:
    put:
      tags:
        - Servers
      description: Overwrites tags assigned for Server and unassigns any tags not part of the request.
      summary: Overwrite tags assigned for Server.
      operationId: serversServerIdTagsPut
      security:
        - OAuth2:
            - bmc
  /servers/{serverId}/actions/provision:
    post:
      tags:
        - Servers
      description: Provision reserved server. Server DNS will be configured to access Google's public DNS at 8.8.8.8.
      summary: Provision server.
      operationId: serversServerIdActionsProvisionPost
      security:
        - OAuth2:
            - bmc
  /servers/{serverId}/actions/deprovision:
    post:
      tags:
        - Servers
      description: Deprovision the server. Supports advanced deprovision configuration.
      summary: Deprovision a server.
      operationId: serversServerIdActionsDeprovisionPost
      security:
        - OAuth2:
            - bmc
  /servers/{serverId}/actions/power-on:
    post:
      tags:
        - Servers
      description: Power on specific server.
      summary: Power on server.
      operationId: serversServerIdActionsPowerOnPost
      security:
        - OAuth2:
            - bmc
  /servers/{serverId}/actions/power-off:
    post:
      tags:
        - Servers
      description: Power off specific server.
      summary: Power off server.
      operationId: serversServerIdActionsPowerOffPost
      security:
        - OAuth2:
            - bmc
  /servers/{serverId}/actions/reboot:
    post:
      tags:
        - Servers
      description: Reboot specific server.
      summary: Reboot server.
      operationId: serversServerIdActionsRebootPost
      security:
        - OAuth2:
            - bmc
  /servers/{serverId}/actions/shutdown:
    post:
      tags:
        - Servers
      description: Shut down specific server.
      summary: Shutdown server.
      operationId: serversServerIdActionsShutdownPost
      security:
        - OAuth2:
            - bmc
  /servers/{serverId}/actions/reset:
    post:
      tags:
        - Servers
      description: 'Deprecated: Reset specific server. Reset only supports network configurations of type ''private network'' or ''IP blocks''. As an alternative, the suggested action is to deprovision the server and provision a new one with the same configuration.'
      summary: Reset server.
      deprecated: true
      operationId: serversServerIdActionsResetPost
      security:
        - OAuth2:
            - bmc
  /servers/{serverId}/actions/reserve:
    post:
      tags:
        - Servers
      description: Reserve specific server.
      summary: Reserve server.
      operationId: serversServerIdActionsReservePost
      security:
        - OAuth2:
            - bmc
  /ssh-keys:
    post:
      tags:
        - SSH Keys
      description: Create an SSH Key. SSH Keys created can be used for server creation and reset functionality.
      summary: Create SSH Key.
      operationId: sshKeysPost
      security:
        - OAuth2:
            - bmc
    get:
      tags:
        - SSH Keys
      description: List all SSH Keys.
      summary: List SSH Keys.
      operationId: sshKeysGet
      security:
        - OAuth2:
            - bmc.read
  /ssh-keys/{sshKeyId}:
    get:
      tags:
        - SSH Keys
      description: Get SSH Key details.
      summary: Get SSH Key.
      operationId: sshKeysSshKeyIdGet
      security:
        - OAuth2:
            - bmc.read
    delete:
      tags:
        - SSH Keys
      description: Delete an SSH Key.
      summary: Delete SSH Key.
      operationId: sshKeysSshKeyIdDelete
      security:
        - OAuth2:
            - bmc
    put:
      tags:
        - SSH Keys
      description: Edit SSH Key details.
      summary: Edit SSH Key.
      operationId: sshKeysSshKeyIdPut
      security:
        - OAuth2:
            - bmc
  /quotas:
    get:
      tags:
        - Quotas
      description: Get account quota details.
      summary: List quotas
      operationId: quotasGet
      security:
        - OAuth2:
            - bmc.read
  /quotas/{quotaId}:
    get:
      tags:
        - Quotas
      description: Get account quota details.
      summary: Get a quota.
      operationId: quotasQuotaIdGet
      security:
        - OAuth2:
            - bmc.read
  /quotas/{quotaId}/actions/request-edit:
    post:
      tags:
        - Quotas
      description: Sends a request to edit the limit of a quota.
      summary: Request quota limit change.
      operationId: quotasQuotaIdActionsRequestEditPost
      security:
        - OAuth2:
            - bmc
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.phoenixnap.com/auth/realms/BMC/protocol/openid-connect/token
          scopes:
            bmc: Grants full access to bmc-api.
            bmc.read: Grants read only access to bmc-api.