openapi: 3.0.2
info:
  title: Networks API
  description: |
    Create, list, edit and delete public/private networks with the Network API. Use public networks to place multiple 
    servers on the same network or VLAN. Assign new servers with IP addresses from the same CIDR range. Use private 
    networks to avoid unnecessary egress data charges. Model your networks according to your business needs.<br>
    <br>
    <span class='pnap-api-knowledge-base-link'>
    Helpful knowledge base articles are available for 
    <a href='https://phoenixnap.com/kb/bmc-server-management-via-api#multi-private-backend-network-api' target='_blank'>multi-private backend networks</a>
    and <a href='https://phoenixnap.com/kb/bmc-server-management-via-api#ftoc-heading-15' target='_blank'>public networks</a>.
    </span><br>
    <br>
    <b>All URLs are relative to (https://api.phoenixnap.com/networks/v1/)</b>
  termsOfService: https://phoenixnap.com/infrastructure-solutions/legal-it/privacy-shield-compliant-privacy-policy
  version: '1.0'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: PhoenixNAP Team
    email: support@phoenixnap.com
    url: https://phoenixnap.com/
servers:
  - url: https://api.phoenixnap.com/networks/v1
security:
  - OAuth2:
      - bmc
      - bmc.read
tags:
  - name: Private Networks
    description: Private Network operations
  - name: Public Networks
    description: Public networks operations
paths:
  /private-networks:
    get:
      tags:
        - Private Networks
      description: List all Private Networks owned by account.
      summary: List Private Networks.
      operationId: privateNetworksGet
      security:
        - OAuth2:
            - bmc.read
    post:
      tags:
        - Private Networks
      description: Create a Private Network.
      summary: Create a Private Network.
      operationId: privateNetworksPost
      security:
        - OAuth2:
            - bmc
  /private-networks/{privateNetworkId}:
    get:
      tags:
        - Private Networks
      description: Retrieve Private Network Details.
      summary: Get a Private Network.
      operationId: privateNetworksNetworkIdGet
      security:
        - OAuth2:
            - bmc.read
    put:
      tags:
        - Private Networks
      description: Update Private Network Details.
      summary: Update a Private Network.
      operationId: privateNetworksNetworkIdPut
      security:
        - OAuth2:
            - bmc
    delete:
      tags:
        - Private Networks
      description: Delete Private Network.
      summary: Delete a Private Network.
      operationId: privateNetworksNetworkIdDelete
      security:
        - OAuth2:
            - bmc
  /public-networks:
    get:
      tags:
        - Public Networks
      description: List all Public Networks owned by account.
      summary: List Public Networks.
      operationId: publicNetworksGet
      security:
        - OAuth2:
            - bmc.read
    post:
      tags:
        - Public Networks
      description: Create a public network.
      summary: Create a public network.
      operationId: publicNetworksPost
      security:
        - OAuth2:
            - bmc
  /public-networks/{publicNetworkId}:
    get:
      tags:
        - Public Networks
      description: Retrieve Public Network Details.
      summary: Get a Public Network.
      operationId: publicNetworksNetworkIdGet
      security:
        - OAuth2:
            - bmc.read
    patch:
      tags:
        - Public Networks
      description: Update Public Network's Details.
      summary: Update Public Network's Details.
      operationId: publicNetworksNetworkIdPatch
      security:
        - OAuth2:
            - bmc
    delete:
      tags:
        - Public Networks
      description: Delete Public Network. The request is accepted only if no resources are members of this network. The IP Block(s) will be freed and can be re-used in the future.
      summary: Delete a Public Network.
      operationId: publicNetworksNetworkIdDelete
      security:
        - OAuth2:
            - bmc
  /public-networks/{publicNetworkId}/ip-blocks:
    post:
      tags:
        - Public Networks
      description: Adds an IP block to this public network.
      summary: Adds an IP block to this public network.
      operationId: publicNetworksNetworkIdIpBlocksPost
      security:
        - OAuth2:
            - bmc
  /public-networks/{publicNetworkId}/ip-blocks/{ipBlockId}:
    delete:
      tags:
        - Public Networks
      description: Removes the IP Block from the Public Network.<br> Please ensure that no resource members within this network have any IPs assigned from the IP Block being removed.<br> Defining `force` query parameter allows resource assigned IP block to be removed anyway.  As a result, traffic addressed to any IP within the block will not be routed to this network anymore.
      summary: Removes the IP Block from the Public Network.
      operationId: publicNetworksNetworkIdIpBlocksIpBlockIdDelete
      security:
        - OAuth2:
            - bmc
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.phoenixnap.com/auth/realms/BMC/protocol/openid-connect/token
          scopes:
            bmc: Grants full access to bmc-api.
            bmc.read: Grants read only access to bmc-api.