openapi: 3.0.2
info:
  title: Network Storage API
  description: |
    Create, list, edit, and delete storage networks with the Network Storage API. Use storage networks to expand storage capacity on a private network.
    <br>
    <span class='pnap-api-knowledge-base-link'>
    Knowledge base articles to help you can be found
    <a href='https://phoenixnap.com/kb/bare-metal-cloud-storage' target='_blank'>here</a>
    </span>
    <br>
    <b>All URLs are relative to (https://api.phoenixnap.com/network-storage/v1/)</b>
  termsOfService: https://phoenixnap.com/infrastructure-solutions/legal-it/privacy-shield-compliant-privacy-policy
  version: '1.0'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: PhoenixNAP Team
    email: support@phoenixnap.com
    url: https://phoenixnap.com/
servers:
  - url: https://api.phoenixnap.com/network-storage/v1
security:
  - OAuth2:
      - networkstorage
      - networkstorage.read
tags:
  - name: Storage Networks
    description: Storage Networks operations.
paths:
  /storage-networks:
    get:
      tags:
        - Storage Networks
      description: List all storage networks.
      summary: List all storage networks.
      operationId: storageNetworksGet
      security:
        - OAuth2:
            - networkstorage.read
    post:
      tags:
        - Storage Networks
      description: Create a storage network and volume.
      summary: Create a storage network and volume.
      operationId: storageNetworksPost
      security:
        - OAuth2:
            - networkstorage
  /storage-networks/{storageId}:
    get:
      tags:
        - Storage Networks
      description: Get storage network details.
      summary: Get storage network details.
      operationId: storageNetworksIdGet
      security:
        - OAuth2:
            - networkstorage.read
    patch:
      tags:
        - Storage Networks
      description: Update storage network details.
      summary: Update storage network details.
      operationId: storageNetworksIdPatch
      security:
        - OAuth2:
            - networkstorage
    delete:
      tags:
        - Storage Networks
      description: Delete a storage network and its volume. A storage network can only be removed if it's not in 'BUSY' state. Billing stops on storage network deletion.
      summary: Delete a storage network and its volume.
      operationId: storageNetworksIdDelete
      security:
        - OAuth2:
            - networkstorage
  /storage-networks/{storageId}/volumes:
    get:
      tags:
        - Storage Networks
      description: Display one or more volumes belonging to a storage network.
      summary: Display one or more volumes belonging to a storage network.
      operationId: storageNetworksStorageNetworkIdVolumesGet
      security:
        - OAuth2:
            - networkstorage.read
    post:
      tags:
        - Storage Networks
      description: Create a volume belonging to a storage network.
      summary: Create a volume belonging to a storage network.
      operationId: storageNetworksStorageNetworkIdVolumesPost
      security:
        - OAuth2:
            - networkstorage
  /storage-networks/{storageId}/volumes/{volumeId}:
    get:
      tags:
        - Storage Networks
      description: Get a storage network's volume details.
      summary: Get a storage network's volume details.
      operationId: storageNetworksStorageNetworkIdVolumesVolumeIdGet
      security:
        - OAuth2:
            - networkstorage.read
    patch:
      tags:
        - Storage Networks
      description: Update a storage network's volume details. Volume's capacity requested cannot be less than or equal to current volume's capacity.
      summary: Update a storage network's volume details.
      operationId: storageNetworksStorageNetworkIdVolumesVolumeIdPatch
      security:
        - OAuth2:
            - networkstorage
    delete:
      tags:
        - Storage Networks
      description: Delete a Storage Network's Volume
      summary: Delete a Storage Network's Volume
      operationId: storageNetworksStorageNetworkIdVolumesVolumeIdDelete
      security:
        - OAuth2:
            - networkstorage
  /storage-networks/{storageId}/volumes/{volumeId}/tags:
    put:
      tags:
        - Storage Networks
      description: Overwrites tags assigned for the volume.
      summary: Overwrites tags assigned for the volume.
      operationId: storageNetworksStorageNetworkIdVolumesVolumeIdTagsPut
      security:
        - OAuth2:
            - networkstorage
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.phoenixnap.com/auth/realms/BMC/protocol/openid-connect/token
          scopes:
            networkstorage: Grants full access to Network Storage API.
            networkstorage.read: Grants read only access to Network Storage API.