name: (abstract) - Test

on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string
      test-suite:
        required: true
        type: string

jobs:
  test:
    name: Test ${{ inputs.module-name }} go v ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    services:
      mockserver:
        image: mockserver/mockserver:5.15.0
        ports:
          - 1080:1080
    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.18', '1.24' ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/test-sdk
        with:
          test-suite: ${{ inputs.test-suite }}
          go-version: ${{ matrix.go-version }}