name: validate-all

on:
  workflow_dispatch:
  workflow_call:
  push:

jobs:  
  # Build stage
  build-and-test-bmcapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: bmcapi
      test-suite: BmcApiTestSuite
  build-and-test-rancherapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: ranchersolutionapi
      test-suite: RancherApiTestSuite
  build-and-test-networkapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: networkapi
      test-suite: NetworkApiTestSuite
  build-and-test-ipapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: ipapi
      test-suite: IpApiTestSuite
  build-and-test-auditapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: auditapi
      test-suite: AuditApiTestSuite
  build-and-test-tagapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: tagapi
      test-suite: TagApiTestSuite
  build-and-test-billingapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: billingapi
      test-suite: BillingApiTestSuite
  build-and-test-networkstorageapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: networkstorageapi
      test-suite: NetworkStorageApiTestSuite
  build-and-test-locationapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: locationapi
      test-suite: LocationApiTestSuite
  build-and-test-invoicingapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: invoicingapi
      test-suite: InvoicingApiTestSuite
  build-and-test-paymentsapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: paymentsapi
      test-suite: PaymentsApiTestSuite

  run-generic-tests:
    uses: ./.github/workflows/_test.yml
    with:
      module-name: "none (generic tests)"
      test-suite: MiscTestSuite

  publish-test-results:
    name: Publish Test Results
    needs:
      - build-and-test-bmcapi
      - build-and-test-rancherapi
      - build-and-test-networkapi
      - build-and-test-ipapi
      - build-and-test-auditapi
      - build-and-test-tagapi
      - build-and-test-billingapi
      - build-and-test-networkstorageapi
      - build-and-test-locationapi
      - build-and-test-invoicingapi
      - build-and-test-paymentsapi
      - run-generic-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: test-reports
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: test-reports/**/*.xml
          check_name: "Test Results"